// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNeA5l7yuYFt3TwsWztoltEyzW0VwodQ',
    appId: '1:546062910978:web:fb91f411ee66cad0f1891b',
    messagingSenderId: '546062910978',
    projectId: 'simplequizapp-415f6',
    authDomain: 'simplequizapp-415f6.firebaseapp.com',
    databaseURL: 'https://simplequizapp-415f6-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-415f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19sHU72q9GEvX_0yu9zAzf9eISGh9ytc',
    appId: '1:546062910978:android:88e9982b7db7d3c2f1891b',
    messagingSenderId: '546062910978',
    projectId: 'simplequizapp-415f6',
    databaseURL: 'https://simplequizapp-415f6-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-415f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEspNJByDCM69GfAEd9OEL8CKJ6P4b4D0',
    appId: '1:546062910978:ios:73ab10dbf7e1be76f1891b',
    messagingSenderId: '546062910978',
    projectId: 'simplequizapp-415f6',
    databaseURL: 'https://simplequizapp-415f6-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-415f6.appspot.com',
    iosClientId: '546062910978-4vde555t1kvmc4osnc3bbla5p5nvqggj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEspNJByDCM69GfAEd9OEL8CKJ6P4b4D0',
    appId: '1:546062910978:ios:73ab10dbf7e1be76f1891b',
    messagingSenderId: '546062910978',
    projectId: 'simplequizapp-415f6',
    databaseURL: 'https://simplequizapp-415f6-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-415f6.appspot.com',
    iosClientId: '546062910978-4vde555t1kvmc4osnc3bbla5p5nvqggj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
